language: csharp

sudo: false  # use the new container-based Travis infrastructure 
dist: xenial

#dotnet 2.* currently fail on unpack
dotnet: 2.1.302

script:
  - ./build.sh BuildNetFramework

branches:
 only:
  - master